class AppStrings {
  static const english = 'English';

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'settings': 'Settings',
      'ai_assistant': 'AI ASSISTANT',
      'notifications': 'Notifications',
      'notifications_subtitle': 'Receive alerts from the AI assistant',
      'keyboard': 'KEYBOARD',
      'ai_keyboard_setup': 'AI Keyboard Setup',
      'ai_keyboard_setup_subtitle': 'Configure Stremini AI Keyboard',
      'switch_keyboard': 'Switch Keyboard',
      'switch_keyboard_subtitle': 'Change your default keyboard',
      'appearance': 'APPEARANCE',
      'theme': 'Theme',
      'languages': 'Languages',
      'privacy': 'PRIVACY',
      'haptic_feedback': 'Haptic Feedback',
      'haptic_feedback_subtitle': 'Vibration on key presses',
      'save_chat_history': 'Save Chat History',
      'save_chat_history_subtitle': 'Store conversations locally',
      'about': 'ABOUT',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms of Service',
      'already_active': 'AI Keyboard is already active',
      'close': 'Close',
      'greeting': "Hello! I'm Stremini AI. How can I help you today?",
      'app_title': 'Stremini AI',
    },
    'Hindi': {
      'settings': 'सेटिंग्स',
      'notifications': 'सूचनाएं',
      'ai_keyboard_setup': 'एआई कीबोर्ड सेटअप',
      'switch_keyboard': 'कीबोर्ड बदलें',
      'theme': 'थीम',
      'languages': 'भाषाएं',
      'haptic_feedback': 'हैप्टिक फीडबैक',
      'save_chat_history': 'चैट इतिहास सहेजें',
      'already_active': 'AI कीबोर्ड पहले से सक्रिय है',
      'close': 'बंद करें',
      'greeting': 'नमस्ते! मैं स्ट्रेमिनी AI हूं। मैं आपकी कैसे मदद कर सकता हूं?',
      'app_title': 'स्ट्रेमिनी AI',
    },
    'Spanish': {
      'settings': 'Configuración',
      'notifications': 'Notificaciones',
      'ai_keyboard_setup': 'Configurar teclado AI',
      'switch_keyboard': 'Cambiar teclado',
      'theme': 'Tema',
      'languages': 'Idiomas',
      'haptic_feedback': 'Respuesta háptica',
      'save_chat_history': 'Guardar historial de chat',
      'already_active': 'El teclado AI ya está activo',
      'close': 'Cerrar',
      'greeting': '¡Hola! Soy Stremini AI. ¿Cómo puedo ayudarte hoy?',
      'app_title': 'Stremini AI',
    },
    'French': {
      'settings': 'Paramètres',
      'notifications': 'Notifications',
      'ai_keyboard_setup': 'Configuration clavier IA',
      'switch_keyboard': 'Changer de clavier',
      'theme': 'Thème',
      'languages': 'Langues',
      'haptic_feedback': 'Retour haptique',
      'save_chat_history': 'Enregistrer l\'historique',
      'already_active': 'Le clavier IA est déjà actif',
      'close': 'Fermer',
      'greeting': 'Bonjour ! Je suis Stremini AI. Comment puis-je vous aider ?',
      'app_title': 'Stremini AI',
    },
    'Arabic': {
      'settings': 'الإعدادات',
      'notifications': 'الإشعارات',
      'ai_keyboard_setup': 'إعداد لوحة المفاتيح الذكية',
      'switch_keyboard': 'تبديل لوحة المفاتيح',
      'theme': 'المظهر',
      'languages': 'اللغات',
      'haptic_feedback': 'الاهتزاز اللمسي',
      'save_chat_history': 'حفظ سجل الدردشة',
      'already_active': 'لوحة المفاتيح الذكية مفعلة بالفعل',
      'close': 'إغلاق',
      'greeting': 'مرحبًا! أنا Stremini AI. كيف يمكنني مساعدتك اليوم؟',
      'app_title': 'Stremini AI',
    },
    'Japanese': {
      'settings': '設定',
      'notifications': '通知',
      'ai_keyboard_setup': 'AIキーボード設定',
      'switch_keyboard': 'キーボード切替',
      'theme': 'テーマ',
      'languages': '言語',
      'haptic_feedback': '触覚フィードバック',
      'save_chat_history': 'チャット履歴を保存',
      'already_active': 'AIキーボードはすでに有効です',
      'close': '閉じる',
      'greeting': 'こんにちは！Stremini AIです。今日はどうしましたか？',
      'app_title': 'Stremini AI',
    },
  };

  static String t(String language, String key) {
    return _translations[language]?[key] ?? _translations[english]![key] ?? key;
  }
}